//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchaserecords
    {
        public int sid { get; set; }
        public int cid { get; set; }
        public int fid { get; set; }
        public System.DateTime purchDate { get; set; }
        public int quantity { get; set; }
        public decimal price { get; set; }
        public decimal settlement { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual food food { get; set; }
    }
}
